stages:
  - build
  - release

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_SETTINGS_PATH: "$CI_PROJECT_DIR/.m2"

before_script:
  - mkdir -p $MAVEN_SETTINGS_PATH
  - echo "<settings><servers><server><id>karmadev_releases</id><username>$MAVEN_USERNAME</username><password>$MAVEN_PASSWORD</password></server><server><id>karmadev_snapshots</id><username>$MAVEN_USERNAME</username><password>$MAVEN_PASSWORD</password></server></servers></settings>" > $MAVEN_SETTINGS_PATH/settings.xml
  - apt-get update -y
  - apt-get install -y jq curl

maven-build:
  image: maven:3.8-openjdk-8
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean deploy -DTARGET_RELEASES=https://nexus.karmadev.es/repository/internal/ -DTARGET_SNAPSHOTS=https://nexus.karmadev.es/repository/snapshots/
    - export VERSION=$(mvn --non-recursive help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-/--/g')
    - version_badge_id=$(curl --header "PRIVATE-TOKEN:$API_TOKEN" https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/badges | jq -c 'map(select(.name | contains("version")))[0].id')
    - curl --request PUT --header "PRIVATE-TOKEN:$API_TOKEN" --data "image_url=https://img.shields.io/badge/version-$VERSION-blue" https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/badges/$version_badge_id
  artifacts:
    name: "Maven artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    paths:
      - "LockLoginBungee/target/LockLogin.jar"
      - "LockLoginSpigot/target/LockLogin.jar"

release:
  stage: release
  script:
    - echo $VERSION > latest_release.txt