stages:
  - build

variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
    -DTARGET_RELEASES=https://nexus.karmadev.es/repository/internal/
    -DTARGET_SNAPSHOTS=https://nexus.karmadev.es/repository/snapshots/
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -DinstallAtEnd=true
    -DdeployAtEnd=true
#  MAVEN_SETTINGS_PATH: "$CI_PROJECT_DIR/.m2"

before_script:
  - mkdir -p $MAVEN_SETTINGS_PATH
  - echo "<settings><servers><server><id>karmadev_releases</id><username>$MAVEN_USERNAME</username><password>$MAVEN_PASSWORD</password></server><server><id>karmadev_snapshots</id><username>$MAVEN_USERNAME</username><password>$MAVEN_PASSWORD</password></server></servers></settings>" > $MAVEN_SETTINGS_PATH/settings.xml
  - apt-get update -qy
  - apt-get install -y maven openjdk-17-jdk

java-build:
  image: maven:3.8-openjdk-8
  stage: build
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
  script:
    - mvn $MAVEN_CLI_OPTS clean deploy -DskipTests=true
  artifacts:
    name: "Maven artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    paths:
      - "LockLoginSpigot/target"
      - "LockLoginBungee/target"