name: Maven Build

on:
  workflow_dispatch: {}
  push:
    branches:
      - master  # ajusta el nombre de tu rama principal si es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TARGET_RELEASES: "https://nexus.karmadev.es/repository/internal/"
      TARGET_SNAPSHOTS: "https://nexus.karmadev.es/repository/snapshots/"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8.0.402+6'

    - name: Create Maven Settings
      run: |
        echo "<settings><servers><server><id>karmadev_releases</id><username>$MAVEN_USERNAME</username><password>$MAVEN_PASSWORD</password></server><server><id>karmadev_snapshots</id><username>$MAVEN_USERNAME</username><password>$MAVEN_PASSWORD</password></server></servers></settings>" > /home/runner/.m2/settings.xml

    - name: Build with Maven
      run: mvn clean deploy

    - name: Archive Maven Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Maven-artifacts
        path: |
          LockLoginBungee/target/LockLogin.jar
          LockLoginSpigot/target/LockLogin.jar
