name: LockLogin
version: "${project.parent.version}"
description: "${project.parent.description}"
author: "KarmaDev"
website: "https://karmadev.es/"
main: ${spigot.main}
database: true
api-version: 1.13
depend:
  - KarmaAPI

softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - floodgate

commands:
  register:
    description: The principal command to create an account
  login:
    description: The principal command to authenticate an user